version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: bloomPass
      MYSQL_DATABASE: winxclub
      MYSQL_USER: bloom
      MYSQL_PASSWORD: bloomPass
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 20s
      timeout: 30s
      retries: 10
      start_period: 10s
    networks:
      - winxnet
  phpmyadmin:
    profiles:
      - dev
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: bloom
      PMA_PASSWORD: bloomPass
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - winxnet
  webscraping:
    profiles:
      - init
    build:
      dockerfile: ./web_scraper/Dockerfile
      context: .
    depends_on:
      - mysql
    networks:
      - winxnet
networks:
  winxnet:
    driver: bridge
